### ISSUE TITLE
For textNodes which are created from `null`, it throws error

### ISSUE THREAD

**Issue by pankajpatel** [modulor-js/modulor-html#10]
https://github.com/modulor-js/modulor-html/blob/0d1701a755831543d3168a7630399d240349c24e/src/html.js#L122

The nodes where the variable is null and is converted to empty string by JS. That empty string is passed as null around the program. like in following case:
```js
const a = null;
console.log(html`${a}`);
```

**Comment by nogizhopaboroda** [comment]
fixed in https://github.com/modulor-js/modulor-html/pull/26
test: https://github.com/modulor-js/modulor-html/blob/master/test/html.test.js#L472
@pankajpatel could you please confirm fix?

**Comment by pankajpatel** [comment]
Yes, the PR fixes the issue. Closing.
